In [1]:
!pip install PyPDF2
!pip install autocorrect

Collecting PyPDF2
  Obtaining dependency information for PyPDF2 from https://files.pythonhosted.org/packages/8e/5e/c86a5643653825d3c913719e788e41386bee415c2b87b4f955432f2de6b2/pypdf2-3.0.1-py3-none-any.whl.metadata
  Downloading pypdf2-3.0.1-py3-none-any.whl.metadata (6.8 kB)
Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 2.1 MB/s eta 0:00:00a 0:00:01m
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1
Collecting autocorrect
  Downloading autocorrect-2.6.1.tar.gz (622 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 622.8/622.8 kB 3.9 MB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: autocorrect
  Building wheel for autocorrect (setup.py) ... done
  Created wheel for autocorrect: filename=autocorrect-2.6.1-py3-none-any.whl size=622363 sha256=feb53e5742f7ce3bf22052a5f9ddb00a39836a12c2ac4eb52f9610f0efad5700
  Stored in directory: /root/.cache/pip/wheels/b5/7b/6d/b76b29ce11ff8e2521c8c7dd0e5bfee4fb1789d76193124343
Successfully built autocorrect
Installing collected packages: autocorrect
Successfully installed autocorrect-2.6.1

In [1]:
import PyPDF2
import string
import nltk
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk import pos_tag , word_tokenize , sent_tokenize
import pandas as pd
import spacy
import re
from autocorrect import Speller
from spacy.matcher import Matcher
import itertools
from gensim.corpora import Dictionary
from gensim.models import TfidfModel
import numpy as np
import matplotlib.pyplot as plt


# Chargez le petit modèle linguistique pour l'anglais et attribuez-le à la variable 'nlp'.
nlp = spacy.load('en_core_web_sm')

#nltk.download('punkt')
#nltk.download('wordnet')
#nltk.download('averaged_perceptron_tagger')
#nltk.download('stopwords')

ModuleNotFoundError: No module named 'PyPDF2'

# Phase 1 Preprocessing

In [3]:
# objet lecteur pdf
pdfFileObj = open('/kaggle/input/pmbok6/PMBOK6-2017.pdf', 'rb')
pdfReader = PyPDF2.PdfReader(pdfFileObj)

In [4]:
# nombre de pages en pdf
print(len(pdfReader.pages))

573

In [5]:
#Extraction de texte à partir de pdf
#(41 pages [de 309 à 354 page] du PMBOK).
writer = PyPDF2.PdfWriter()
for i in range(430,494):
    my_page = pdfReader.pages[i]
    writer.add_page(my_page)
output_filename = 'PROJECT_RISK_MANAGEMENT.pdf'
with open(output_filename, 'wb') as output:
    writer.write(output)

In [6]:
pdfFileObj = open('/kaggle/working/PROJECT_RISK_MANAGEMENT.pdf', 'rb')

In [7]:
PROJECT_RISK_MANAGEMENT = PyPDF2.PdfReader(pdfFileObj)
print(len(PROJECT_RISK_MANAGEMENT.pages))

64

## PROJECT_RISK_MANAGEMENT

In [8]:
text=""
for i in range(0, len(PROJECT_RISK_MANAGEMENT.pages)):
    page=PROJECT_RISK_MANAGEMENT.pages[i]
    text=text+page.extract_text()
text=text.replace("\n","")

# Extraction de Chaque processus

### PlanRiskManagement

In [9]:
PlanRiskManagement=""
for i in range(0,14):
    page=PROJECT_RISK_MANAGEMENT.pages[i]
    PlanRiskManagement=PlanRiskManagement+page.extract_text()
PlanRiskManagement=PlanRiskManagement.replace("\n","")

### IdentifyRisks

In [11]:
IdentifyRisks=""
for i in range(14,24):
    page=PROJECT_RISK_MANAGEMENT.pages[i]
    IdentifyRisks=IdentifyRisks+page.extract_text()
IdentifyRisks=IdentifyRisks.replace("\n","")

### PerformQualitativeRiskAnalysis

In [12]:
PerformQualitativeRiskAnalysis=""
for i in range(24,33):
    page=PROJECT_RISK_MANAGEMENT.pages[i]
    PerformQualitativeRiskAnalysis=PerformQualitativeRiskAnalysis+page.extract_text()
PerformQualitativeRiskAnalysis=PerformQualitativeRiskAnalysis.replace("\n","")

### PerformQuantitativeRisk

In [13]:
PerformQuantitativeRisk=""
for i in range(33,42):
    page=PROJECT_RISK_MANAGEMENT.pages[i]
    PerformQuantitativeRisk=PerformQuantitativeRisk+page.extract_text()
PerformQuantitativeRisk=PerformQuantitativeRisk.replace("\n","")

### PlanRiskResponses

In [14]:
PlanRiskResponses=""
for i in range(42,54):
    page=PROJECT_RISK_MANAGEMENT.pages[i]
    PlanRiskResponses=PlanRiskResponses+page.extract_text()
PlanRiskResponses=PlanRiskResponses.replace("\n","")

### ImplementRiskResponses

In [15]:
ImplementRiskResponses=""
for i in range(54, 58):
    page=PROJECT_RISK_MANAGEMENT.pages[i]
    ImplementRiskResponses=ImplementRiskResponses+page.extract_text()
ImplementRiskResponses=ImplementRiskResponses.replace("\n","")

### MonitorRisks

In [16]:
MonitorRisks=""
for i in range(58,64):
    page=PROJECT_RISK_MANAGEMENT.pages[i]
    MonitorRisks=MonitorRisks+page.extract_text()
MonitorRisks=MonitorRisks.replace("\n","")

In [17]:
#dataframe pour tout les processus
df_processes=pd.DataFrame([PlanRiskManagement,IdentifyRisks,PerformQualitativeRiskAnalysis,PerformQuantitativeRisk,PlanRiskResponses,ImplementRiskResponses,MonitorRisks],columns=["processes"])
df_processes["nom_processes"]=["PlanRiskManagement","IdentifyRisks","PerformQualitativeRiskAnalysis","PerformQuantitativeRisk","PlanRiskResponses","ImplementRiskResponses","MonitorRisks"]

In [18]:
df_processes=df_processes[["nom_processes","processes"]]

In [19]:
df_processes

,nom_processes,processes
0,PlanRiskManagement,"Not For Distribution, Sale or Reproduction.395..."
1,IdentifyRisks,"Not For Distribution, Sale or Reproduction.409..."
2,PerformQualitativeRiskAnalysis,"Not For Distribution, Sale or Reproduction.419..."
3,PerformQuantitativeRisk,"Not For Distribution, Sale or Reproduction.428..."
4,PlanRiskResponses,"Not For Distribution, Sale or Reproduction.437..."
5,ImplementRiskResponses,"Not For Distribution, Sale or Reproduction.449..."
6,MonitorRisks,"Not For Distribution, Sale or Reproduction.453..."

In [20]:
def clean(text):
    
    # Suppression des numéros de paragraphe
    text = re.sub('[0-9]+.[0-9]+.[0-9]+.[0-9]+\t',' ',str(text))
    text = re.sub('[0-9]+.[0-9]+.[0-9]+\t',' ',str(text))
    text = re.sub('[0-9]+.[0-9]+\t',' ',str(text))
    text = re.sub('[[0-9]+.]+\t',' ',str(text))
    text = re.sub('[0-9]+.[0-9]+.[0-9]+.[0-9]+ ',' ',str(text))
    text = re.sub('[0-9]+.[0-9]+.[0-9]+ ',' ',str(text))
    text = re.sub('[0-9]+.[0-9]+ ',' ',str(text))
    text = re.sub('[[0-9]+.]+ ',' ',str(text))
    text = re.sub('[.[0-9]+]+\t',' ',str(text))
    text = re.sub('[.[0-9]+.]+ ',' ',str(text))
    # Suppression des numéros de page
    #text = re.sub('[0-9]+©2013 ',' ',str(text))
    # Suppression de l'en-tête et du pied de page
    #text = re.sub('Project Management Institute.',' ',str(text))
    #text = re.sub('Licensed To: Jorge Diego Fuentes Sanchez PMI MemberID: 2399412This copy is a PMI Member benefit, not for distribution, sale, or reproduction.','',str(text))
    # suppression des caractères de la nouvelle ligne
    text = re.sub('\n ',' ',str(text))
    text = re.sub('\n',' ',str(text))
    text = re.sub(':',' conceptualise ',str(text))
    text = re.sub('†','',str(text))
    # supprimer les apostrophes
    text = re.sub("™","'",text)
    text = re.sub("¥","'",text)
    text = re.sub("'s","'",str(text))
    # suppression des traits d'union
    text = re.sub("-",' ',str(text))
    text = re.sub("— ",'',str(text))
    # suppression des guillemets
    text = re.sub('\"',' ',str(text))
    text = re.sub('“',' ',str(text))
    # suppression de toute référence
    text = re.sub("[\(\[].*?[\)\]]", " ", str(text))
    text = re.sub("[ ]+"," ",str(text))
    # correction de texte
    text = re.sub("˜","fi",text)
    text = re.sub("˚","kn",text)
    text = re.sub("Š"," ",text)
    text = re.sub(","," ",text)
    text = re.sub("PMBOK®","PMBOK",text)
    text = re.sub("INTRODUCTIONINTRODUCTIONA","A",text)
    text = re.sub("PROJECT RISK MANAGEMENTPROJECT RISK MANAGEMENT"," ",text)
    text = re.sub('A Guide to the Project Management Body of Knowledge Œ Fifth Edition 11 A Guide to the Project Management Body of Knowledge Œ Fifth Edition ','A Guide to the Project Management Body of Knowledge Œ Fifth Edition ',str(text))
    text = re.sub('A Guide to the Project Management Body of Knowledge Œ Fifth Edition ',' ',str(text))
    text = re.sub("PROJECT RI SK MANAGEMENTProject Risk Management"," ",text)
    text = re.sub("IDENTI FY RISKSIdentify Risks"," ",text)
    text = re.sub("PERFORM QUALI TATIVE RISK A NALYSISPerform Qualitative Risk Analysis"," ",text)
    text = re.sub("Part Guide PERFORM QUANTI TATIVE RISK A NALYSISPerform Quantitative Risk Analysis"," ",text)
    text = re.sub("PLAN RISK R ESPONSESPlan Risk Responses"," ",text)
    text = re.sub("Control RisksControl Risks"," ",text)
    text = re.sub("IMPLEMENT RISK R ESPONSESImplement Risk Responses"," ",text)
    text = re.sub("MONI TOR RISKSMonitor Risks"," ",text)
    text = re.sub("Not For Distribution Sale or Reproduction.? ?"," ",text)
    text = re.sub("Not For Distribution Sale or Reproduction. "," ",text)
    text = re.sub('Œ','',text)
    text = re.sub('[0-9]+','',str(text))
    # supprimer les répétitions d'espace
    text = re.sub("[ ]+"," ",str(text))
    
    return text

In [21]:
#Fonction pour éliminer les ponctuations
def remove_punctuation(text_original):
    text_no_punctuation = text_original.translate(str.maketrans('', '', string.punctuation))
    return(text_no_punctuation)

In [22]:
#Fonction pour supprimer les caractères spéciaux
def remove_special(text_original):
    text_no_punctuation = text_original.translate(str.maketrans('', '', '™ŒŠ˚˜©®œ'))
    return(text_no_punctuation)

In [23]:
spell = Speller(lang='en')

In [24]:
df_processes["processes"]=df_processes["processes"].apply(lambda s : clean(s))
df_processes["processes"]=df_processes["processes"].apply(lambda s : remove_special(s))
# Suppression des "stop words"(THE)
df_processes["processes"]=df_processes["processes"].apply(lambda s : " ".join([word for word in s.split() if word != "the" ]))

/tmp/ipykernel_48/472506940.py:7: FutureWarning: Possible nested set at position 1
  text = re.sub('[[0-9]+.]+\t',' ',str(text))
/tmp/ipykernel_48/472506940.py:11: FutureWarning: Possible nested set at position 1
  text = re.sub('[[0-9]+.]+ ',' ',str(text))

In [25]:
df_processes

,nom_processes,processes
0,PlanRiskManagement,Not For Distribution Sale or Reproduction. inc...
1,IdentifyRisks,Not For Distribution Sale or Reproduction. is ...
2,PerformQualitativeRiskAnalysis,Not For Distribution Sale or Reproduction. is ...
3,PerformQuantitativeRisk,Not For Distribution Sale or Reproduction. Par...
4,PlanRiskResponses,Not For Distribution Sale or Reproduction. is ...
5,ImplementRiskResponses,Not For Distribution Sale or Reproduction. is ...
6,MonitorRisks,Not For Distribution Sale or Reproduction. is ...

#  Sentence Tokenization

In [26]:
#ségementation des phrases par processus
sentences_p0=sent_tokenize( df_processes["processes"][0] )
sentences_p1=sent_tokenize( df_processes["processes"][1] )
sentences_p2=sent_tokenize( df_processes["processes"][2] )
sentences_p3=sent_tokenize( df_processes["processes"][3] )
sentences_p4=sent_tokenize( df_processes["processes"][4] )
sentences_p5=sent_tokenize( df_processes["processes"][5] )
sentences_p6=sent_tokenize( df_processes["processes"][6] )
df_0=pd.DataFrame(sentences_p0,columns=["sentence"])
df_1=pd.DataFrame(sentences_p1,columns=["sentence"])
df_2=pd.DataFrame(sentences_p2,columns=["sentence"])
df_3=pd.DataFrame(sentences_p3,columns=["sentence"])
df_4=pd.DataFrame(sentences_p4,columns=["sentence"])
df_5=pd.DataFrame(sentences_p5,columns=["sentence"])
df_6=pd.DataFrame(sentences_p6,columns=["sentence"])
df_0["nom_process"]="PlanRiskManagement"
df_1["nom_process"]="IdentifyRisks"
df_2["nom_process"]="PerformQualitativeRiskAnalysis	"
df_3["nom_process"]="PerformQuantitativeRisk"
df_4["nom_process"]="PlanRiskResponses"
df_5["nom_process"]="ImplementRiskResponses"
df_6["nom_process"]="MonitorRisks"

In [27]:
#dataframe pour tout les phrases de chaque processus
df=df_0._append(df_1)._append(df_2)._append(df_3)._append(df_4)._append(df_5)._append(df_6)

In [28]:
df=df[["nom_process","sentence"]]

In [32]:
df.head(20)

           nom_process                                           sentence
0   PlanRiskManagement          not for distribution sale or reproduction
1   PlanRiskManagement  includes processes of conducting risk manageme...
2   PlanRiskManagement  objectives of project risk management are to i...
3   PlanRiskManagement  identify risks — process of identifying indivi...
4   PlanRiskManagement  perform qualitative risk analysis — process of...
5   PlanRiskManagement  perform quantitative risk analysis — process o...
6   PlanRiskManagement  plan risk responses — process of developing op...
7   PlanRiskManagement  implement risk responses — process of implemen...
8   PlanRiskManagement  monitor risks — process of monitoring implemen...
9   PlanRiskManagement  project management risk processes are presente...
10  PlanRiskManagement                                   part guidefigure
11  PlanRiskManagement                   project risk management overview
12  PlanRiskManagement                                             inputs
13  PlanRiskManagement                                    project charter
14  PlanRiskManagement                            project management plan
15  PlanRiskManagement                                  project documents
16  PlanRiskManagement                   enterprise environmental factors
17  PlanRiskManagement                      organizational process assets
18  PlanRiskManagement                                   tools techniques
19  PlanRiskManagement                                    expert judgment

In [30]:
# rendre le text en miniscule
df["sentence"]=df["sentence"].apply(lambda s : s.lower())
#suppresion des ponctuation
df["sentence"]=df["sentence"].apply(lambda s : remove_punctuation(s))
#suprression des "stop words "
df["sentence"]=df["sentence"].apply(lambda s : " ".join([word.text for word in nlp(s) if not word.pos_ in ["ADV"]]))
df["sentence"] = df["sentence"].apply(lambda s : " ".join([word for word in s.split() if word != "the" ]))

# Text Lemmatization and Stemming

In [33]:
!unzip -o /usr/share/nltk_data/corpora/wordnet -d /usr/share/nltk_data/corpora/

Archive:  /usr/share/nltk_data/corpora/wordnet.zip
   creating: /usr/share/nltk_data/corpora/wordnet/
  inflating: /usr/share/nltk_data/corpora/wordnet/lexnames
  inflating: /usr/share/nltk_data/corpora/wordnet/data.verb
  inflating: /usr/share/nltk_data/corpora/wordnet/index.adv
  inflating: /usr/share/nltk_data/corpora/wordnet/adv.exc
  inflating: /usr/share/nltk_data/corpora/wordnet/index.verb
  inflating: /usr/share/nltk_data/corpora/wordnet/cntlist.rev
  inflating: /usr/share/nltk_data/corpora/wordnet/data.adj
  inflating: /usr/share/nltk_data/corpora/wordnet/index.adj
  inflating: /usr/share/nltk_data/corpora/wordnet/LICENSE
  inflating: /usr/share/nltk_data/corpora/wordnet/citation.bib
  inflating: /usr/share/nltk_data/corpora/wordnet/noun.exc
  inflating: /usr/share/nltk_data/corpora/wordnet/verb.exc
  inflating: /usr/share/nltk_data/corpora/wordnet/README
  inflating: /usr/share/nltk_data/corpora/wordnet/index.sense
  inflating: /usr/share/nltk_data/corpora/wordnet/data.noun
  inflating: /usr/share/nltk_data/corpora/wordnet/data.adv
  inflating: /usr/share/nltk_data/corpora/wordnet/index.noun
  inflating: /usr/share/nltk_data/corpora/wordnet/adj.exc

In [34]:
# la différence entre (Lemmatization) et Stemming
def compare_stemmer_and_lemmatizer(stemmer, lemmatizer, word, pos):
    """
    Print the results of stemmind and lemmitization using the passed stemmer, lemmatizer, word and pos (part of speech)
    """
    print("Stemmer:", stemmer.stem(word))
    print("Lemmatizer:", lemmatizer.lemmatize(word, pos))
    print()

lemmatizer = WordNetLemmatizer()
stemmer = PorterStemmer()
compare_stemmer_and_lemmatizer(stemmer, lemmatizer, word = "studies", pos = wordnet.VERB)
compare_stemmer_and_lemmatizer(stemmer, lemmatizer, word = "very", pos = wordnet.VERB)

Stemmer: studi
Lemmatizer: study

Stemmer: veri
Lemmatizer: very

## Lemmatization

In [35]:
lemmatizer = WordNetLemmatizer()
def lemm(s):
    l = []
    for word, tag in pos_tag(word_tokenize(s)):
        wntag = tag[0].lower()
        wntag = wntag if wntag in ['a', 'r', 'n', 'v'] else None
        lemma = lemmatizer.lemmatize(word, wntag) if wntag else word
        l.append(lemma)
    return l

In [36]:
# application de la lemmatization sur tout le text
df["sentence"]=df["sentence"].apply(lambda s : " ".join(lemm(s)))

In [37]:
df.head()

          nom_process                                           sentence
0  PlanRiskManagement          not for distribution sale or reproduction
1  PlanRiskManagement  include process of conduct risk management pla...
2  PlanRiskManagement  objective of project risk management be to inc...
3  PlanRiskManagement  identify risk — process of identify individual...
4  PlanRiskManagement  perform qualitative risk analysis — process of...

### Synonyms

In [38]:
# reduire le nombre des mots avec les synonymes
def syns(s):
    l = []
    for w in nlp(s):
        syn = wordnet.synsets(w.text)
        a = w.text
        if len(syn) > 0 and w.pos_ in ['NN', 'VB']:
            a = syn[0].name().split('.')[0]
        l.append(a)
    return l

In [39]:
syn = wordnet.synsets("hi")
syn[0].name().split('.')[0]

'hello'

In [40]:
df["sentence"]=df["sentence"].apply(lambda s: " ".join(syns(s)))

# Word Tokenisation

In [41]:
#ségementation des phrases en des mots avec "word tokenize"
tokens=[word_tokenize(sent) for sent in df["sentence"]]
df["tokens"]=tokens

In [42]:
df

,nom_process,sentence,tokens
0,PlanRiskManagement,not for distribution sale or reproduction,"[not, for, distribution, sale, or, reproduction]"
1,PlanRiskManagement,include process of conduct risk management pla...,"[include, process, of, conduct, risk, manageme..."
2,PlanRiskManagement,objective of project risk management be to inc...,"[objective, of, project, risk, management, be,..."
3,PlanRiskManagement,identify risk — process of identify individual...,"[identify, risk, —, process, of, identify, ind..."
4,PlanRiskManagement,perform qualitative risk analysis — process of...,"[perform, qualitative, risk, analysis, —, proc..."
...,...,...,...
70,MonitorRisks,this may include add new risk update outdated ...,"[this, may, include, add, new, risk, update, o..."
71,MonitorRisks,describe in section as new information become ...,"[describe, in, section, as, new, information, ..."
72,MonitorRisks,risk report may include detail of top individu...,"[risk, report, may, include, detail, of, top, ..."
73,MonitorRisks,it may include conclusion from risk audit on e...,"[it, may, include, conclusion, from, risk, aud..."
74,MonitorRisks,organizational proce s asse t upda tesorganiza...,"[organizational, proce, s, asse, t, upda, teso..."

In [43]:
from nltk import bigrams, trigrams

In [45]:
#Extraction des bigrams et trigrams
df["bigrams"]=df["tokens"].apply(lambda s : [a for a in bigrams(s)])
df["trigrams"]=df["tokens"].apply(lambda s : [a for a in trigrams(s)])

In [ ]:
df.head()

### Visualizing long texts

In [47]:
from spacy import displacy
doc=nlp(df["sentence"].values[154])
displacy.render(doc, style='dep',jupyter=True)

## Named Entity Extraction PMBOK

In [49]:
def entityExtraction(rawtext):
    doc = nlp(rawtext)
    d = []
    for ent in doc.ents:
        d.append((ent.label_, ent.text))
        df_entity = pd.DataFrame(d, columns=('named entity', 'output'))
    return df_entity

In [51]:
df_entity = entityExtraction(". ".join(df.sentence))
df_entity = df_entity.loc[df_entity['named entity'] != 'PERSON']
df_entity = df_entity.loc[df_entity['named entity'] != 'ORG']

In [64]:
df_entity.head(20)

   named entity                  output
0      CARDINAL                     two
1      CARDINAL                     one
2           FAC                    ng p
3      CARDINAL                     two
7          NORP                     tec
10     CARDINAL                   three
11         DATE  month month month week
22          GPE              docum enta
23         NORP                     tec
27     CARDINAL                     one
33         NORP                     tec
34      PRODUCT  theringdata ga thering
36     CARDINAL                     one
37     CARDINAL                     one
38     CARDINAL                     one
39     CARDINAL                     one
40     CARDINAL                     one
41     CARDINAL           more than two
42     CARDINAL                   three
43     CARDINAL                   three

### PMI Practice Standard for Project Risk Management

In [53]:
PMIpdfFileObj = open('/kaggle/input/pmi-practice-standard-project-risk-management/practice-standard-project-risk-management.pdf', 'rb')

In [54]:
# objet lecteur pdf
PMIpdfReader = PyPDF2.PdfReader(pdffile)

In [55]:
# nombre de pages en pdf
print(len(PMIpdfReader.pages))

128

In [57]:
#extraction du text de PMI
textPMI=""
for i in range(0,len(PMIpdfReader.pages)):
    page=PMIpdfReader.pages[i]
    textPMI=textPMI+page.extract_text()
textPMI=textPMI.replace("\n","")

In [58]:
textPMI_clean=clean(textPMI)
textPMI_clean=remove_special(textPMI_clean)

In [59]:
#ségementation des phrases
pmi_sent=sent_tokenize(textPMI_clean)

In [60]:
df_pmi=pd.DataFrame(pmi_sent,columns=["sentence"])

In [61]:
# rendre le text en miniscule
df_pmi["sentence"]=df_pmi["sentence"].apply(lambda s : s.lower())
# supression des punctuations 
df_pmi["sentence"]=df_pmi["sentence"].apply(lambda s : remove_punctuation(s))
# suppresion des stop words
df_pmi["sentence"]=df_pmi["sentence"].apply(lambda s : " ".join([word.text for word in nlp(s) if not word.pos_ in ["ADV"]]))
df_pmi["sentence"]=df_pmi["sentence"].apply(lambda s : " ".join([word for word in s.split() if word != "the" ]))
# Lemmatization
df_pmi["sentence"]=df_pmi["sentence"].apply(lambda s : " ".join(lemm(s)))

In [62]:
df_pmi.head()

                                            sentence
0  project management institute practice standard...
1  phone conceptualise fax conceptualise e mail c...
2  pmi ” pmi logo pmp ” pmp logo pmbok ” pgmp ” p...
3  quarter globe design be a trademark of project...
4  pmi publication welcome correction and comment...

### Named Entity Extraction PMI

In [63]:
df_entity_pmi = entityExtraction(". ".join(df_pmi.sentence))
df_entity_pmi = df_entity_pmi.loc[df_entity_pmi['named entity'] != 'PERSON']
df_entity_pmi = df_entity_pmi.loc[df_entity_pmi['named entity'] != 'ORG']

In [65]:
df_entity_pmi.head()

   named entity     output
5          DATE      today
7      CARDINAL    quarter
18     CARDINAL      three
20          LAW  chapter −
21      ORDINAL     fourth

# Phase 2

### Extraction des titres

In [66]:
# Extraction de la partie table des matieres
writer = PyPDF2.PdfWriter()
Context=""
for i in range(4,15):
    my_page = pdfReader.pages[i]
    Context=Context+my_page.extract_text()
Context=Context.replace("\n"," ").replace("..","")

In [67]:
# fonction pour l'extraction du text entre deux strings
def extract_text(text,startT,endT):
    start = text.find(startT) + len(startT)
    end = text.find(endT)
    substring = text[start:end]
    return substring

In [68]:
#Fonction pour éliminer les chiffres
def remove_numeric(text_original):
    text_no_numeric = text_original.translate(str.maketrans('','',string.digits))
    return(text_no_numeric)

In [69]:
#extraction des nom de processes
processes=[]
for i in range (1,7):
    processes.append(remove_numeric(extract_text(Context,"11."+str(i),"11."+str(i)+".1")).lower().replace('.','').strip())

In [70]:
processes

['plan risk management',
 'identify risks',
 'perform qualitative risk analysis',
 'perform quantitative risk analysis',
 'plan risk responses',
 'implement risk responses']

In [71]:
#focntion pour extraire les sous-titre de chaque process
def extract_process_headlines(p):
    L=[]
    for i in range (1,3):
        L.append(remove_numeric(extract_text(Context,"11."+str(p)+"."+str(i),"11."+str(p)+"."+str(i+1))).lower().replace('.','').strip())
        output=remove_numeric(extract_text(Context,"11."+str(p)+'.3','11.'+str(p+1))).lower().replace('.','')
        output=extract_text(output,output[0],'outputs')
    L.append(output+"outputs")
    return L

In [72]:
#les sous titres du process plan risk management:
extract_process_headlines(1)

['plan risk management: inputs',
 'plan risk management: tools and techniques',
 'plan risk management: outputs']

In [ ]:
processes

In [73]:
#Extraction de la partie project risk mangemenet
text2=""
for i in range(0,len(PROJECT_RISK_MANAGEMENT.pages)):
    page=PROJECT_RISK_MANAGEMENT.pages[i]
    text2=text2+page.extract_text()
text2=text2.replace("\n","")

In [75]:
#fonction pour retourner le nombre de chaque process
def get_number(p,part):
    number=0
    K=0
    if part=="inputs":
        k=1
    elif part=="tools and techniques":
        k=2
    elif part=="outputs":
        k=3
    else:
        return 0
    for i in range(1,14):
        if '11.'+str(p)+'.'+str(k)+'.'+str(i) in text2:
            number=number+1
    return (number)

In [76]:
#plan risk management possede 5 inputs
get_number(1,'inputs')

5

In [77]:
ll=extract_text(text2,"11.1.1.2","11.1.1.3")
ll

' PROJECT MANAGEM ENT PLANDescribed in Section 4.2.3.1. In planning Project Risk Management, all approved subsidiary management plans should be taken into consideration in order to make the risk management plan consistent with them. The methodology outlined in other project management plan components might inﬂuence the Plan Risk Management process.'

In [79]:
#extraction du titre de la défintion 
def extract_title(annotation):
    match = re.search(r"[A-Z\s]", annotation)
    if match:
        start = match.start()
        end = start
        while end < len(annotation) and (annotation[end].isupper() or annotation[end].isspace()):
            end += 1
        return annotation[start:end-1]
    else:
        return ""

In [80]:
extract_title(ll)

' PROJECT MANAGEM ENT PLAN'

In [81]:
#fonction pour extraire les titres et les annotations
def extract_process_inforamtion(p,Type):
    if Type=="inputs":
        t=1
    elif Type=="tools and techniques":
        t=2
    elif Type=="outputs":
        t=3
    N=get_number(p,Type)
    titles=[]
    annotations=[]
    for i in range(1,N):
        start="11."+str(p)+"."+str(t)+"."+str(i)
        end="11."+str(p)+"."+str(t)+"."+str(i+1)
        annotation=extract_text(text2,start,end)
        titles.append(extract_title(annotation))
        annotations.append(annotation.strip()) 
    annotation=extract_text(text2,"11."+str(p)+"."+str(t)+"."+str(N),"11."+str(p)+"."+str(t+1))
    titles.append(extract_title(annotation))
    annotations.append(annotation)
    return titles,annotations

In [82]:
text2 = re.sub('[0-9]+©2013 ',' ',str(text2))
text2 = re.sub('Licensed To: Jorge Diego Fuentes Sanchez PMI MemberID: 2399412This copy is a PMI Member benefit, not for distribution, sale, or reproduction.','',str(text))
text2 = text2.replace("Techniques Interviewing","TechniquesInterviewing")
text2 = text2.replace("A Guide to the Project Management Body of Knowledge (PMBOK® Guide) Œ Fifth Edition 11 - PROJECT RISK MANAGEMENT","")
text2 = text2.replace("Examples of Commonly Used Probability Distributions Project Management Institute.","")
text2 = text2.replace("SWOT","Swot")
# afficher les "tools and techniques" du process plan risk management
extract_process_inforamtion(1,"tools and techniques")

([' EXPER T JUDGMENT', ' DATA ANALY SIS', ' MEETIN GS'],
 ['EXPER T JUDGMENTDescribed in Section 4.1.2.1. Expertise should be considered from individuals or groups with specialized knowledge or training in the following topics:uuFamiliarity with the organization’s approach to managing risk, including enterprise risk management where this is performed;uuTailoring risk management to the speciﬁc needs of a project; anduuTypes of risk that are likely to be encountered on projects in the same area.',
  'DATA ANALY SISData analysis techniques that can be used for this process includes but are not limited to a stakeholder analysis (Section 13.1.2.3) to determine the risk appetite of project stakeholders.',
  ' MEETIN GSThe risk management plan may be developed as part of the project kick-off meeting or a speciﬁc planning meeting may be held. Attendees may include the project manager, selected project team members, key stakeholders, or team members who are responsible to manage the risk management process on the project. Others outside the organization may also be invited, as needed, including customers, sellers, and regulators. A skilled facilitator can help participants remain focused on the task, agree on key aspects of the risk approach, identify and overcome sources of bias, and resolve any disagreements that may arise.Plans for conducting risk management activities are deﬁned in these meetings and documented in the risk management plan (see Section '])

In [83]:
sents=sent_tokenize(text2.replace("PROJECT RISK MANAGEMENT11"," ").replace("A Guide to the Project Management Body of Knowledge (PMBOK® Guide) Œ Fifth Edition 11 -","").replace("Assumptions may be incorporated into the project scope statement or in a separate assumptions log.",""))

In [84]:
#extraction les annotations de chaque process
def extractProcessAnnotations():
    annotations=[]
    for i in range(1,7):
        annotation=""
        for sent in sents:
            if sent.startswith('11.'+str(i)+' ') or sent.startswith('.'+str(i)+' '):
                annotation=annotation+" "+sent.replace('˜','fi')  
                i=int(sents.index(sent))
                while(i>0):
                    i=i+1
                    annotation=annotation+" "+sents[i].replace('˜','fi')
                    if sents[i].startswith('The inputs, tools and techniques'):
                        i=-1
        annotations.append(annotation)
        return annotations

In [86]:
#creation du dataframe is/have (nom_process /is a /project risk managment)
dlist=[]
for p in range(0,6):
    dis_dict = {'Noun1':processes[p],'Is/Have':'is a','Noun2':'project risk management'}
    dlist.append(dis_dict)
df_title=pd.DataFrame(dlist)

In [87]:
df_title

                                Noun1 Is/Have                    Noun2
0                plan risk management    is a  project risk management
1                      identify risks    is a  project risk management
2   perform qualitative risk analysis    is a  project risk management
3  perform quantitative risk analysis    is a  project risk management
4                 plan risk responses    is a  project risk management
5            implement risk responses    is a  project risk management

In [88]:
# creation du datframe pours les concepts et les sous concepts
dlist=[]
for p in range(0,6):
    for i in range(0,3):
        dis_dict = {'parent concept':processes[p],'conceptualise':'conceptualise','concept':extract_process_headlines(p+1)[i].replace(':','')}
        dlist.append(dis_dict)
df_Parent_Concept=pd.DataFrame(dlist)

In [89]:
df_Parent_Concept

,parent concept,conceptualise,concept
0,plan risk management,conceptualise,plan risk management inputs
1,plan risk management,conceptualise,plan risk management tools and techniques
2,plan risk management,conceptualise,plan risk management outputs
3,identify risks,conceptualise,identify risks inputs
4,identify risks,conceptualise,identify risks tools and techniques
5,identify risks,conceptualise,identify risks outputs
6,perform qualitative risk analysis,conceptualise,perform qualitative risk analysis inputs
7,perform qualitative risk analysis,conceptualise,perform qualitative risk analysis tools and te...
8,perform qualitative risk analysis,conceptualise,perform qualitative risk analysis outputs
9,perform quantitative risk analysis,conceptualise,perform quantitative risk analysis inputs
10,perform quantitative risk analysis,conceptualise,perform quantitative risk analysis tools and t...
11,perform quantitative risk analysis,conceptualise,perform quantitative risk analysis outputs
12,plan risk responses,conceptualise,plan risk responses inputs
13,plan risk responses,conceptualise,plan risk responses tools and techniques
14,plan risk responses,conceptualise,plan risk responses outputs
15,implement risk responses,conceptualise,implement risk responses inputs
16,implement risk responses,conceptualise,implement risk responses tools and techniques
17,implement risk responses,conceptualise,implement risk responses outputs

In [90]:
extract_process_inforamtion(2,"inputs")[0]

[' PROJECT MANAGEM ENT PLAN',
 ' PROJECT DOCUM ENTS',
 ' AGREEM ENTS',
 ' PROC UREM ENT DOCUM ENTA TION',
 ' ENTERPR ISE ENVIRONM ENTAL  FACTORS',
 ' ORGANIZATIONAL  PROCE SS ASSE TS']

In [91]:
#fonction pour la creation du dataframe is a /have a
def extract_IOTT(Filter):
    dlist=[]
    for p in range(1,7):
        N=extract_process_inforamtion(p,Filter)[0]
        for i in range(0,len(N)):
            dis_dict = {'Noun1':N[i],'Is/Have':'is a','Noun2':processes[p-1]+" "+Filter}
            dlist.append(dis_dict)
    df_IOTT=pd.DataFrame(dlist)
    return df_IOTT

In [92]:
df_IOTT=extract_IOTT("inputs")._append(extract_IOTT("tools and techniques"))._append(extract_IOTT("outputs"))

In [93]:
df_IOTT.head()

                                  Noun1 Is/Have                        Noun2
0                      PROJECT CHAR TER    is a  plan risk management inputs
1              PROJECT MANAGEM ENT PLAN    is a  plan risk management inputs
2                   PROJE CT DOCUM ENTS    is a  plan risk management inputs
3   ENTERPR ISE ENVIRONM ENTAL  FACTORS    is a  plan risk management inputs
4      ORGANIZATIONAL  PROCE SS ASSE TS    is a  plan risk management inputs

In [94]:
df_title=df_title._append(df_IOTT)

In [95]:
df_title

,Noun1,Is/Have,Noun2
0,plan risk management,is a,project risk management
1,identify risks,is a,project risk management
2,perform qualitative risk analysis,is a,project risk management
3,perform quantitative risk analysis,is a,project risk management
4,plan risk responses,is a,project risk management
...,...,...,...
6,CHANG E REQUESTS,is a,plan risk responses outputs
7,PROJECT MANAGEM ENT PLAN UPDA TES,is a,plan risk responses outputs
8,PROJECT DOCUM ENTS UPDA TES,is a,plan risk responses outputs
9,CHANG E REQUESTS,is a,implement risk responses outputs
10,PROJECT DOCUM ENTS UPDA TES,is a,implement risk responses outputs

In [96]:
docPMBOK = nlp(". ".join(df.sentence))

In [97]:
# Extraction des noms PMBOK
AllNounsPMBOK=[]
for tok in docPMBOK:
    if tok.pos_=="NOUN":
        AllNounsPMBOK.append(tok.text)

In [98]:
docPMI = nlp(". ".join(df_pmi.sentence))

In [99]:
# Extraction des noms PMI
AllNounsPMI=[]
for tok in docPMI:
    if tok.pos_=="NOUN":
        AllNounsPMI.append(tok.text)

In [100]:
# fonction de recherche des synonymes
def find_synonym_ontology(word):
    synonyms = []
    for syn in wordnet.synsets(word):
        for lm in syn.lemmas():
            synonyms.append(lm.name())
    return list(set(synonyms))

In [101]:
# Examples
print("Synonyms of project : ", find_synonym_ontology("project"))
print("Synonyms of management: ", find_synonym_ontology("management"))
print("Synonyms of change: ", find_synonym_ontology("risk"))

Synonyms of project :  ['design', 'jut_out', 'propose', 'fancy', 'projection', 'project', 'cast', 'visualise', 'plan', 'send_off', 'visualize', 'see', 'throw', 'image', 'task', 'contrive', 'figure', 'externalise', 'protrude', 'stick_out', 'labor', 'jut', 'undertaking', 'externalize', 'picture', 'envision']
Synonyms of management:  ['management', 'direction']
Synonyms of change:  ['jeopardy', 'take_chances', 'run_a_risk', 'adventure', 'lay_on_the_line', 'put_on_the_line', 'risk', 'take_a_chance', 'endangerment', 'risk_of_exposure', 'gamble', 'danger', 'hazard', 'risk_of_infection', 'chance', 'peril']

In [102]:
# fonction de recherche des synonymes dans le PMBOK
def synonymConceptOntoPMB(term):
    if term not in AllNounsPMBOK :
        return []
    else :
        syno_list=[]
        temp_list=[]
        syno_list = find_synonym_ontology(term)
        if len(syno_list) != 0 :
            for syno  in syno_list :
                if syno in AllNounsPMBOK  and syno != term :
                    temp_list.append(syno)
                    
        return temp_list

### Find synonym in PBMOK

In [103]:
print("Synonym of project in our ontology :", synonymConceptOntoPMB('project'))
print("Synonym of risk in our ontology :", synonymConceptOntoPMB('risk'))
print("Synonym of management in our ontology :", synonymConceptOntoPMB('management'))

Synonym of project in our ontology : ['design', 'plan', 'task', 'figure', 'undertaking']
Synonym of risk in our ontology : ['jeopardy', 'chance']
Synonym of management in our ontology : ['direction']

In [104]:
# fonction de recherche des synonymes dans le PMI
def synonymConceptintoPMI(term):
    if term not in AllNounsPMBOK :
        return [] 
    else :
        syno_list=[]
        temp_list=[]
        syno_list = find_synonym_ontology(term)
        if len(syno_list) != 0 :
            for syno  in syno_list :
                if syno in AllNounsPMI  and syno != term and (syno not in synonymConceptOntoPMB(term)) :
                    temp_list.append(syno)                    
        return temp_list

### Find synonym in PMI

In [105]:
print("Synonym of project in PMI :", synonymConceptintoPMI('project'))
print("Synonym of project in our ontology :", synonymConceptOntoPMB('project'))

Synonym of project in PMI : ['projection', 'see', 'image', 'picture']
Synonym of project in our ontology : ['design', 'plan', 'task', 'figure', 'undertaking']

### EXTRACTION DES RÉGLES

In [106]:
#spacy matching
def Y_X(doc):
    m = []
    #défintion des patternes
    pattern = [{'DEP':'compound', 'OP':"*"},
               {'POS':'NOUN'},
               {'LOWER': 'such'},
               {'LOWER': 'as'},
               {'DEP':'compound', 'OP':"*"},
               {'POS': 'NOUN'}
              ]
    pattern2 = [{'DEP':'compound', 'OP':"*"},
               {'POS':'NOUN'},
               {'LOWER': 'like'},
               {'DEP':'compound', 'OP':"*"},
               {'POS': 'NOUN'}
              ]
    pattern3 = [{'DEP':'compound', 'OP':"*"},
               {'POS':'NOUN'},
               {'LOWER': 'including'},
               {'DEP':'compound', 'OP':"*"},
               {'POS': 'NOUN'}
              ]
    matcher = Matcher(nlp.vocab)
    matcher.add("matching_1",[pattern,pattern2,pattern3],on_match=None)
    matches = matcher(doc)
    spans = [doc[start:end] for _, start, end in matches]
    for span in spacy.util.filter_spans(spans):
        m.append(re.split('( such as )',span.text))
    df_m = pd.DataFrame(m,columns=['Y','Relation','X'])
    return df_m

In [107]:
doc1 = nlp(". ".join(df[df["nom_process"]=="PlanRiskManagement"].sentence))
doc2 = nlp(". ".join(df[df["nom_process"]=="IdentifyRisks"].sentence))
doc3 = nlp(". ".join(df[df["nom_process"]=="PerformQualitativeRiskAnalysis"].sentence))
doc4 = nlp(". ".join(df[df["nom_process"]=="PerformQuantitativeRisk"].sentence))
doc5 = nlp(". ".join(df[df["nom_process"]=="PlanRiskResponses"].sentence))
doc6 = nlp(". ".join(df[df["nom_process"]=="ImplementRiskResponses"].sentence))
doc7 = nlp(". ".join(df[df["nom_process"]=="MonitorRisks"].sentence))

In [108]:
Y_X(docPMI).head()

                     Y   Relation                                           X
0                forum   such as                              handbook manual
1          environment   such as                       stakeholder scope time
2             ciencies   such as                                      address
3  risk relate feature   such as                                        cause
4            technique   such as   estimate plan cost control task allocation

In [109]:
# fonction pour enrichir les régles "spacy matching relation" de PMI
def Y_X_enrichementPMI(docPMI):
    m=[]
    for X,Y in itertools.zip_longest(Y_X(docPMI).X, Y_X(docPMI).Y):
        if(len(synonymConceptOntoPMB(Y))+len(synonymConceptOntoPMB(X)) > 0):
            s=spell(Y)+" such as "+spell(X)
            m.append(re.split('( such as )',s))
    df_m = pd.DataFrame(m,columns=['Y','Relation','X'])
    return df_m

In [110]:
df_Y_X=Y_X(docPMBOK)._append(Y_X_enrichementPMI(docPMI)).drop_duplicates().reset_index(drop=True)

In [111]:
df_Y_X.head()

,Y,Relation,X
0,problem,such as,delay cost overrun performance shortfall
1,information,such as,milestone date contract type acceptance criterion
2,project variable,such as,size
3,project risk,such as,number
4,project objective,such as,schedule cost quality

In [112]:
df_Parent_Concept.head()

,parent concept,conceptualise,concept
0,plan risk management,conceptualise,plan risk management inputs
1,plan risk management,conceptualise,plan risk management tools and techniques
2,plan risk management,conceptualise,plan risk management outputs
3,identify risks,conceptualise,identify risks inputs
4,identify risks,conceptualise,identify risks tools and techniques

In [113]:
df_Parent_Concept

,parent concept,conceptualise,concept
0,plan risk management,conceptualise,plan risk management inputs
1,plan risk management,conceptualise,plan risk management tools and techniques
2,plan risk management,conceptualise,plan risk management outputs
3,identify risks,conceptualise,identify risks inputs
4,identify risks,conceptualise,identify risks tools and techniques
5,identify risks,conceptualise,identify risks outputs
6,perform qualitative risk analysis,conceptualise,perform qualitative risk analysis inputs
7,perform qualitative risk analysis,conceptualise,perform qualitative risk analysis tools and te...
8,perform qualitative risk analysis,conceptualise,perform qualitative risk analysis outputs
9,perform quantitative risk analysis,conceptualise,perform quantitative risk analysis inputs
10,perform quantitative risk analysis,conceptualise,perform quantitative risk analysis tools and t...
11,perform quantitative risk analysis,conceptualise,perform quantitative risk analysis outputs
12,plan risk responses,conceptualise,plan risk responses inputs
13,plan risk responses,conceptualise,plan risk responses tools and techniques
14,plan risk responses,conceptualise,plan risk responses outputs
15,implement risk responses,conceptualise,implement risk responses inputs
16,implement risk responses,conceptualise,implement risk responses tools and techniques
17,implement risk responses,conceptualise,implement risk responses outputs

### Subject-Predicate-Object Rule with Compound Nouns

In [114]:
def rule2_mod(text,index):
    doc = nlp(text)
    phrase = ''
    for token in doc:
        if token.i == index:
            for subtoken in token.children:
                if (subtoken.dep_ == 'compound'):
                    phrase += subtoken.text + ' '
            break
    return phrase

In [115]:
def rule1_mod(text):
    doc = nlp(text)
    sent = []
    for token in doc:
        # root word
        if (token.pos_=='VERB'):
            #phrase =''
            ph = []
            # only extract noun or pronoun subjects
            for sub_tok in token.lefts:
                if (sub_tok.dep_ in ['nsubj','nsubjpass']) and (sub_tok.pos_ in ['NOUN','PROPN','PRON']):
                    phrase =''
                    # look for subject modifier
                    adj = rule2_mod(text,sub_tok.i)
                    phrase += adj + sub_tok.text
                    ph.append(phrase)
                    # save the root word of the word
                    #phrase += ' '+token.text#.lemma_
                    ph.append(token.text)
                    # check for noun or pronoun direct objects
                    for sub_tok in token.rights:
                        if (sub_tok.dep_ in ['dobj','pobj']) and (sub_tok.pos_ in ['NOUN','PROPN','PRON']):
                            phrase =''
                            # look for object modifier
                            adj = rule2_mod(text,sub_tok.i)
                            phrase += adj+sub_tok.text
                            ph.append(phrase)
                            sent.append(ph)
    return sent

In [116]:
def SubjectPredicateObje(df):
    row_list = []
    for i in range(len(df)):
        sent = df.sentence.values[i]
        output = rule1_mod(sent)
        dict1 = {'Sentence':sent,'Output':output}
        row_list.append(dict1)
    
    df_rule = pd.DataFrame(row_list)
    df_show = pd.DataFrame(columns=df_rule.columns)

    for row in range(len(df_rule)):
        if len(df_rule.loc[row,'Output'])!=0:
            df_show = df_show._append(df_rule.loc[row,:])

    # reset the index
    df_show.reset_index(inplace=True)
    df_show.drop('index',axis=1,inplace=True)    

    # separate subject, verb and object
    verb_dict = dict()
    dis_dict = dict()
    dis_list = []

    # iterating over all the sentences
    for i in range(len(df_show)):
        # sentence containing the output
        sentence = df_show.loc[i,'Sentence']
        # output of the sentence
        output = df_show.loc[i,'Output']
        # iterating over all the outputs from the sentence
        for sent in output:
            # separate subject, verb and object
            #n1, v, n2 = sent.split()[:1], sent.split()[1], sent.split()[2:]
            n1, v, n2 = sent[:1], sent[1], sent[2:]
            # append to list, along with the sentence
            dis_dict = {'Sentence':sentence,'Subject':n1,'Predicate':v,'Object':n2}
            dis_list.append(dis_dict)
            # counting the number of sentences containing the verb
            #verb = sent.split()[1]
            verb = sent[1]
            if verb in verb_dict:
                verb_dict[verb]+=1
            else:
                verb_dict[verb]=1

    df_sep = pd.DataFrame(dis_list)
    row_list = []
    row_list2 = []

    for i in range(len(df_sep)):
        sent = df_sep.loc[i,'Subject']
        s = " ".join(sent)
        row_list.append(s)
        sent = df_sep.loc[i,'Object']
        s = " ".join(sent)
        row_list2.append(s)
    
    df_sep['Subject'] = row_list
    df_sep['Object'] = row_list2
    
    return df_sep

In [117]:
df_sep_pmbok=SubjectPredicateObje(df)

In [118]:
df_sep_pmi=SubjectPredicateObje(df_pmi)

In [ ]:
df_sep_pmbok.head()

In [ ]:
df_sep_pmi.head()

In [ ]:
df_sep_pmbok.columns

In [ ]:
# fonction pour enrichir les régles "Subject,Predicate,Object" de PMI
def SPO_enrichment(df):
    m=[]
    for Sentence,Subject,Object,Predicate in itertools.zip_longest(df.Sentence,df.Subject, df.Object,df.Predicate):
        if(len(synonymConceptOntoPMB(Subject))+len(synonymConceptOntoPMB(Object)) > 0):
                s=[]
                s.append(Sentence)
                s.append(spell(Subject))
                s.append(spell(Predicate))
                s.append(spell(Object))
                m.append(s)
                df_co = pd.DataFrame(m,columns=['Sentence','Subject','Predicate','Object'])

    return df_co

In [ ]:
df_spo=df_sep_pmbok._append(SPO_enrichment(df_sep_pmi)).drop_duplicates().reset_index(drop=True)

In [ ]:
len(df_spo)

In [ ]:
df_spo

### "Is A/ Have A" Rule

In [ ]:
def rule4(text):
    doc = nlp(text)
    sent = []
    for token in doc:
        # if the token is a verb
        if (token.text in ['have','be','may','cloud','can','should','will']):
            ph =[]
            # only extract noun or pronoun subjects
            for sub_tok in token.lefts:
                if (sub_tok.pos_ in ['NOUN','PROPN','PRON']):
                    phrase =''
                    # add subject to the phrase
                    adj = rule2_mod(text,sub_tok.i)
                    phrase += adj + sub_tok.text
                    ph.append(phrase)
                    # save the root of the verb in phrase
                    #phrase += ' '+token.text#.lemma_
                    ph.append(token.text)
                    # check for noun or pronoun direct objects
                    for sub_tok in token.rights:
                        # save the object in the phrase
                        if (sub_tok.pos_ in ['NOUN','PROPN','PRON']):
                            phrase =''
                            adj = rule2_mod(text,sub_tok.i)
                            phrase += adj+sub_tok.text
                            ph.append(phrase)
                            sent.append(ph)
            
    return sent

In [ ]:
def RuleIsaHavea(df):
    row_list = []
    for i in range(len(df)):
        sent = df.sentence.values[i]
        output = rule4(sent)
        dict1 = {'Sentence':sent,'Output':output}
        row_list.append(dict1)
    df_rule4_all = pd.DataFrame(row_list)
    df_show4 = pd.DataFrame(columns=df_rule4_all.columns)
    for row in range(len(df_rule4_all)):
        if len(df_rule4_all.loc[row,'Output'])!=0:
            df_show4 = df_show4._append(df_rule4_all.loc[row,:])
    # reset the index
    df_show4.reset_index(inplace=True)
    df_show4.drop('index',axis=1,inplace=True)
    prep_dict = dict()
    dis_dict = dict()
    dis_list = []
    # iterating over all the sentences
    for i in range(len(df_show4)):
        # sentence containing the output
        sentence = df_show4.loc[i,'Sentence']
        # output of the sentence
        output = df_show4.loc[i,'Output']
        # iterating over all the outputs from the sentence
        for sent in output:
            # separate subject, verb and object
            n1, p, n2 = sent[:1], sent[1], sent[2:]
            # append to list, along with the sentence
            dis_dict = {'Sentence':sentence,'Noun1':n1,'Is/Have':p,'Noun2':n2}
            dis_list.append(dis_dict)
            # counting the number of sentences containing the verb
            prep = sent[1]
            if prep in prep_dict:
                prep_dict[prep]+=1
            else:
                prep_dict[prep]=1
    df_sep4= pd.DataFrame(dis_list)
    df_sep4['Is/Have'] = df_sep4['Is/Have'].replace('have','has a')
    df_sep4['Is/Have'] = df_sep4['Is/Have'].replace('be','is a')
    row_list = []
    row_list2 = []

    for i in range(len(df_sep4)):
        sent = df_sep4.loc[i,'Noun1']
        s = " ".join(sent)
        row_list.append(s)
        sent = df_sep4.loc[i,'Noun2']
        s = " ".join(sent)
        row_list2.append(s)

    df_sep4['Noun1'] = row_list
    df_sep4['Noun2'] = row_list2
    return df_sep4

In [ ]:
df_pmi_IsaHavea=RuleIsaHavea(df_pmi)
df_pmbok_IsaHavea=RuleIsaHavea(df)

In [ ]:
df_pmi_IsaHavea.head()

In [ ]:
df_pmbok_IsaHavea.head()

In [ ]:
# enrichir les régles "is/have a" de PMI
def IsaHaveaPmiEnrichment(df):
    m=[]
    for Sentence,Noun1,relation,Noun2 in itertools.zip_longest(df.Sentence,df.Noun1, df["Is/Have"],df.Noun2):
        if(len(synonymConceptOntoPMB(Noun1))+len(synonymConceptOntoPMB(Noun2)) > 0):
                s=[]
                s.append(Sentence)
                s.append(spell(Noun1))
                s.append(spell(relation))
                s.append(spell(Noun2))
                m.append(s)
                df_sep = pd.DataFrame(m,columns=['Sentence','Noun1','Is/Have','Noun2'])

    return df_sep

In [ ]:
df_IsaHavea=df_pmbok_IsaHavea._append(IsaHaveaPmiEnrichment(df_pmi_IsaHavea)).drop_duplicates().reset_index(drop=True)

In [ ]:
df_IsaHavea

In [ ]:
df_Y_X.head()

In [ ]:
df_Parent_Concept.head()

In [ ]:
df_IsaHavea.head()

In [ ]:
df_spo.head()

### Remove outliners

In [ ]:
df_IsaHavea = df_IsaHavea[df_IsaHavea['Noun1'].str.len() < 25 ][~df_IsaHavea['Noun1'].isin(['it','there','they']) ].drop_duplicates().reset_index(drop = True)
df_IsaHavea = df_IsaHavea[df_IsaHavea['Noun2'].str.len() < 25 ][~df_IsaHavea['Noun2'].isin(['it','there','they']) ].drop_duplicates().reset_index(drop = True)

df_spo = df_spo[df_spo['Subject'].str.len() < 25][~df_spo['Subject'].isin(['it','there','they'])].drop_duplicates().reset_index(drop = True)
df_spo = df_spo[df_spo['Object'].str.len() < 25][~df_spo['Object'].isin(['it','there','they'])].drop_duplicates().reset_index(drop = True)

df_Y_X = df_Y_X[df_Y_X['X'].str.len() < 25][~df_Y_X['X'].isin(['it','there','they'])].drop_duplicates().reset_index(drop = True)
df_Y_X = df_Y_X[df_Y_X['Y'].str.len() < 25][~df_Y_X['Y'].isin(['it','there','they'])].drop_duplicates().reset_index(drop = True)

In [ ]:
df_IsaHavea = df_IsaHavea._append(df_title).drop_duplicates().reset_index(drop = True)

In [ ]:
df_IsaHavea=df_IsaHavea.fillna("")
df_IsaHavea=df_IsaHavea[["Sentence","Noun1","Is/Have","Noun2"]]

In [ ]:
df_IsaHavea["Noun1"]=df_IsaHavea["Noun1"].apply(lambda s : s.lower())
df_IsaHavea["Noun2"]=df_IsaHavea["Noun2"].apply(lambda s : s.lower())

In [ ]:
df_IsaHavea

### Chunking with NLTK

In [ ]:
tokens=[]
for i in range(0,len(df)):
    tokens=tokens+df.tokens.values[i]

In [ ]:
tags=nltk.pos_tag(tokens)

In [ ]:
import nltk
#"NP:{<DT>?<JJ>*<NN>}"
grammar="Chunk:{<NN.?><VB.?><JJ>*<NN.?>}"
chunkParser = nltk.RegexpParser(grammar)
chunked = chunkParser.parse(tags)

In [ ]:
[ i for i in chunked  if type(i)==type(chunked[2])][:10]

### English Stop words

In [ ]:
stop_words = set(stopwords.words("english"))
#print(stop_words)

In [ ]:
def removeStopWords(tokens):
    return [token for token in tokens if token  not in stop_words]

In [ ]:
#Suppression des STOP WORDS
df["tokens"]=df["tokens"].apply(lambda s : removeStopWords(s))

## Retrieval Proceess Evaluation

### TFIDF Measure

In [ ]:
processed_docs = df.tokens
dct = Dictionary(processed_docs)
print(dct)

In [ ]:
bow_corpus = [dct.doc2bow(doc) for doc in processed_docs]
df_corpus = pd.DataFrame(np.array(bow_corpus[0])[:,1], index = np.unique(df.tokens.values[0]), columns=['Frequency'])
df_corpus

In [ ]:
bow_doc_0 = bow_corpus[0]
for i in range(3):
    print("Word {} (\"{}\") appears {} time.".format(bow_doc_0[i][0], 
                                               dct[bow_doc_0[i][0]], 
bow_doc_0[i][1]))

In [ ]:
from wordcloud import WordCloud, STOPWORDS
import imageio
import matplotlib.pyplot as plt
import nltk


# Get 100 words based on the 
words_except_stop_dist = nltk.FreqDist(w for w in tokens[:100]) 
wordcloud = WordCloud(stopwords=set(STOPWORDS),background_color='black').generate(" ".join(words_except_stop_dist))
plt.imshow(wordcloud,interpolation = 'bilinear')
fig=plt.gcf()
fig.set_size_inches(10,12)
plt.axis('off')
plt.title("Top most common 100 words PMBOK",fontsize=20)
plt.tight_layout(pad=0)
plt.savefig('PMBOK_cost_time_scop_top_100.jpeg')

In [ ]:
model_tfidf = TfidfModel(bow_corpus,normalize=True)

In [ ]:
corpus_tfidf = model_tfidf[bow_corpus]
df_tfidf = pd.DataFrame(np.array(corpus_tfidf[0])[:,1], index = np.unique(df.tokens.values[0]), columns=['TFIDF'])
df_tfidf

In [ ]:
f, ax = plt.subplots(figsize=(20,10))
plt.bar(list(df_tfidf.index.values), list(df_tfidf.TFIDF.values))
plt.xlabel('Corpus')
plt.ylabel('TFIDF')
plt.title('TFIDF Model')

# Phase 4 OWL Extraction

## Entities Organization (Concepts/Individuals/Properties/Attributes)

### Extract concepts and individuals from named entities

In [ ]:
df_entity=df_entity._append(df_entity_pmi)

In [ ]:
df_entity.head()

In [ ]:
df_concept = df_entity[['named entity']].drop_duplicates().reset_index(drop=True)
df_concept['concept'] = df_concept['named entity'].str.lower()
df_concept = df_concept.drop(['named entity'], axis=1).drop_duplicates().reset_index(drop=True)
df_concept

In [ ]:
df_individual = df_entity.drop_duplicates().reset_index(drop=True)
df_individual['concept'] = df_individual['named entity'].str.lower()
df_individual['individual'] = df_individual['output'].str.lower()
df_individual = df_individual.drop(['named entity','output'], axis=1).sort_values('concept').drop_duplicates().reset_index(drop=True)
df_individual.head()

### Extract concepts and individuals from Spacy Matching

In [ ]:
df_ind2 = df_Y_X[['X','Y']].drop_duplicates().reset_index(drop=True).rename(columns={'X':'individual','Y':'concept'})
df_con2 = df_ind2[['concept']].drop_duplicates().reset_index(drop=True)

In [ ]:
df_ind2.head()

In [ ]:
df_con2.head()

In [ ]:
df_concept = df_concept._append([df_con2]).drop_duplicates().reset_index(drop=True)
df_individual = df_individual._append([df_ind2]).drop_duplicates().reset_index(drop=True)

In [ ]:
df_concept.head()

In [ ]:
df_individual.head()

### Extract concepts and sub-concepts from Rule "is a"

In [ ]:
df_csc = df_IsaHavea[df_IsaHavea['Is/Have']=='is a'][['Noun1','Noun2']].drop_duplicates().reset_index(drop=True).rename(columns={'Noun1':'concept','Noun2':'parent concept'})
df_con3 = df_csc[['concept']].drop_duplicates().reset_index(drop=True)
df_con32 = df_csc[['parent concept']].rename(columns={'parent concept':'concept'}).drop_duplicates().reset_index(drop=True)
df_ind3 = df_csc[df_csc['concept'].isin(df_individual['individual'])].drop_duplicates().reset_index(drop=True).rename(columns={'concept':'individual','parent concept':'concept'})
df_csc = df_csc[~df_csc['concept'].isin(df_individual['individual'])][['concept','parent concept']].drop_duplicates().reset_index(drop=True)._append([df_Parent_Concept]).drop_duplicates().reset_index(drop=True)

In [ ]:
df_csc.tail()

In [ ]:
df_concept = df_concept._append([df_con3,df_con32]).drop_duplicates().reset_index(drop=True)
df_individual = df_individual._append([df_ind3]).drop_duplicates().reset_index(drop=True)

### Extract data properties and object properties from Rule "Subject Predicate Object"

A Predicate B -> if A and B are individuals then Predicate is an object property

A Predicate B -> if A is an individual and B is not then Predicate is a data property

if A Predicate B, A Predicate C and B and C are Individuals then B et C have the same type(concept)

In [ ]:
df_have = df_IsaHavea[df_IsaHavea['Is/Have']=='has a'].drop_duplicates().reset_index(drop=True).rename(columns={'Noun1':'Subject','Noun2':'Object','Is/Have':'Predicate'})
df_have['Predicate'] = 'have'
df_sep = df_spo._append([df_have]).drop_duplicates().reset_index(drop=True)
df_pred = df_sep[df_sep['Subject'].isin(df_individual['individual'])]
df_pred = df_pred[df_pred['Subject'] != 'it'].drop_duplicates().reset_index(drop=True)
df_pred.head()

In [ ]:
df_objprop = df_pred[df_pred['Object'].isin(df_individual['individual'])].reset_index(drop=True)
#df_objprop.head()

In [ ]:
df_rest = df_pred[~df_pred['Object'].isin(df_individual['individual'])].reset_index(drop=True)
df_rest.head()

In [ ]:
df_newind= df_rest[df_rest['Subject'].isin(df_objprop['Subject']) & df_rest['Predicate'].isin(df_objprop['Predicate'])].reset_index(drop=True)

In [ ]:
row_list = []
for i in range(len(df_newind)):
    for j in range(len(df_objprop)):
        if df_newind.loc[i,'Subject'] == df_objprop.loc[j,'Subject'] and df_newind.loc[i,'Predicate'] == df_objprop.loc[j,'Predicate']:
            concept = df_objprop.loc[j,'Object']
            row_list.append([df_newind.loc[i,'Object'],concept])

df_temp = pd.DataFrame(row_list,columns=['individual','concept'])
df_individual = df_individual._append([df_temp]).drop_duplicates(subset='individual',keep='last').reset_index(drop=True)

In [ ]:
df_individual.tail()

In [ ]:
df_pred = df_sep[df_sep['Subject'].isin(df_individual['individual'])][['Subject','Predicate','Object']]
df_pred = df_pred[df_pred['Subject'] != 'it'].drop_duplicates().reset_index(drop=True)
df_objprop = df_pred[df_pred['Object'].isin(df_individual['individual'])].drop_duplicates().reset_index(drop=True)
df_objprop = df_objprop.rename(columns={'Predicate':'Object Property'})

In [ ]:
df_dataprop = df_pred[~df_pred['Object'].isin(df_individual['individual'])].drop_duplicates().reset_index(drop=True)
df_dataprop = df_dataprop.rename(columns={'Predicate':'Data Property'})
df_dataprop.head()

In [ ]:
df_pred = df_sep[df_sep['Subject'].isin(df_concept['concept'])][['Subject','Predicate','Object']]
df_pred = df_pred[df_pred['Subject'] != 'it'].drop_duplicates().reset_index(drop=True)
df_objprop_domaine1 = df_pred[df_pred['Object'].isin(df_concept['concept'])].drop_duplicates().reset_index(drop=True)
df_objprop_domaine1 = df_objprop_domaine1.rename(columns={'Predicate':'Object Property', 'Subject':'Domaine','Object':'Range'})
df_objprop_domaine1.head()

In [ ]:
df_dataprop_domaine1 = df_pred[~df_pred['Object'].isin(df_concept['concept'])].drop_duplicates().reset_index(drop=True)
df_dataprop_domaine1 = df_dataprop_domaine1.rename(columns={'Predicate':'Data Property', 'Subject':'Domaine','Object':'Range'})
df_dataprop_domaine1['Range'] = "string"
df_dataprop_domaine1 = df_dataprop_domaine1.drop_duplicates().reset_index(drop=True)
df_dataprop_domaine1.head()

In [ ]:
def get_concept(individual):
    for i in range(len(df_individual)):
        if df_individual.loc[i,'individual'] == individual:
            return df_individual.loc[i,'concept']

In [ ]:
df_objprop_domaine = df_objprop.copy()
df_objprop_domaine['Domaine'] = df_objprop_domaine['Subject'].apply(get_concept)
df_objprop_domaine['Range'] = df_objprop_domaine['Object'].apply(get_concept)
df_objprop_domaine = df_objprop_domaine.drop(columns=['Subject','Object']).drop_duplicates().reset_index(drop=True)
df_objprop_domaine = df_objprop_domaine._append([df_objprop_domaine1]).drop_duplicates().reset_index(drop=True)

In [ ]:
df_dataprop_domaine = df_dataprop.copy()
df_dataprop_domaine['Domaine'] = df_dataprop_domaine['Subject'].apply(get_concept)
df_dataprop_domaine['Range'] = "string"
df_dataprop_domaine = df_dataprop_domaine.drop(columns=['Subject','Object']).drop_duplicates().reset_index(drop=True)
df_dataprop_domaine = df_dataprop_domaine._append([df_dataprop_domaine1]).drop_duplicates().reset_index(drop=True)

In [ ]:
def change(w):
    if(w == 'knowledge'):
        return 'knowledge area'
    return w

In [ ]:
df_concept = df_concept[df_concept['concept'] != 'there'].drop_duplicates().reset_index(drop=True)
df_csc = df_csc[df_csc['concept'] != df_csc['parent concept']].drop_duplicates().reset_index(drop=True)

df_concept['concept'] = df_concept['concept'].apply(change)
df_individual['concept'] = df_individual['concept'].apply(change)
df_csc['concept'] = df_csc['concept'].apply(change)
df_csc['parent concept'] = df_csc['parent concept'].apply(change)
df_dataprop_domaine['Domaine'] = df_dataprop_domaine['Domaine'].apply(change)
df_objprop_domaine['Domaine'] = df_objprop_domaine['Domaine'].apply(change)
df_objprop_domaine['Range'] = df_objprop_domaine['Range'].apply(change)

In [ ]:
def prefix_ind(w):
    for i in range(len(df_individual)):
        if df_individual.loc[i,'individual'] == w:
            return df_individual.loc[i,'concept']+'_'+w
    return w

df_dataprop['Subject'] = df_dataprop['Subject'].apply(prefix_ind)
df_objprop['Subject'] = df_objprop['Subject'].apply(prefix_ind)
df_objprop['Object'] = df_objprop['Object'].apply(prefix_ind)
df_individual['individual'] = df_individual['individual'].apply(prefix_ind)

In [ ]:
def prefix_prop(s,typ):
    lst = []
    if typ == 'Data Property':
        df = df_dataprop_domaine
    else:
        df = df_objprop_domaine
    for j in range(len(s)):
        l = s.loc[j,typ]
        for i in range(len(df)):
            if df.loc[i,typ] == s.loc[j,typ] and df.loc[i,'Domaine'] == get_concept(s.loc[j,'Subject']):
                l= df.loc[i,'Domaine'][0]+df.loc[i,'Range'][0]+'_'+s.loc[j,typ]
        lst.append(l)
    return lst

def prefix_prop_domaine(s,typ):
    lst = []
    for j in range(len(s)):
        l= s.loc[j,'Domaine'][0]+s.loc[j,'Range'][0]+'_'+s.loc[j,typ]
        lst.append(l)
    return lst

df_dataprop['Data Property'] = prefix_prop(df_dataprop,'Data Property')
df_objprop['Object Property'] = prefix_prop(df_objprop,'Object Property')
df_dataprop_domaine['Data Property'] = prefix_prop_domaine(df_dataprop_domaine,'Data Property')
df_objprop_domaine['Object Property'] = prefix_prop_domaine(df_objprop_domaine,'Object Property')

In [ ]:
df_know = pd.DataFrame([['project risk management','knowledge area']],columns=['concept','parent concept'])
df_csc = df_csc._append(df_know).drop_duplicates().reset_index(drop = True)
df_dataprop_domaine = df_dataprop_domaine.drop_duplicates().reset_index(drop = True)
df_objprop_domaine = df_objprop_domaine.drop_duplicates().reset_index(drop = True)
df_individual = df_individual.drop_duplicates().reset_index(drop = True)
df_concept = df_concept.drop_duplicates().reset_index(drop = True)

## Transformer des entités en OWL

In [ ]:
!pip install rdflib

In [ ]:
from rdflib.namespace import DC, DCTERMS, DOAP, FOAF, OWL, RDF, RDFS, SKOS, VOID, XMLNS, XSD
from rdflib import URIRef, BNode, Literal, Namespace, Graph
from rdflib.extras import describer

In [ ]:
g = Graph()
g.bind("owl",OWL)
g.bind("pr","http://example.org/projet#")
ns_url = "http://example.org/projet#"
g.add((URIRef('http://example.org/projet'), RDF.type, OWL.Ontology ))

### Ajouter Classes et Sous-Classes

In [ ]:
for c in df_concept['concept']:
    cl = URIRef(ns_url+c.replace(" ","_"))
    g.add((cl, RDF.type, OWL.Class))
    for i in range(len(df_csc)):
        if df_csc.loc[i,'concept'] == c:
            clp = URIRef(ns_url+df_csc.loc[i,'parent concept'].replace(" ","_"))
            g.add((cl, RDFS.subClassOf, clp))

### Ajouter Data Proprietes

In [ ]:
for i in range(len(df_dataprop_domaine)):
    c = URIRef(ns_url+df_dataprop_domaine.loc[i,'Data Property'].replace(" ","_"))
    domaine = URIRef(ns_url+df_dataprop_domaine.loc[i,'Domaine'].replace(" ","_"))
    g.add((c,RDF.type,OWL.DatatypeProperty))
    g.add((c,RDFS.domain,domaine))
    g.add((c,RDFS.range,XSD.string))

### Ajouter Object Proprietes

In [ ]:
for i in range(len(df_objprop_domaine)):
    c = URIRef(ns_url+df_objprop_domaine.loc[i,'Object Property'].replace(" ","_"))
    domaine = URIRef(ns_url+df_objprop_domaine.loc[i,'Domaine'].replace(" ","_"))
    rang = URIRef(ns_url+df_objprop_domaine.loc[i,'Range'].replace(" ","_"))
    g.add((c,RDF.type,OWL.ObjectProperty))
    g.add((c,RDFS.domain,domaine))
    g.add((c,RDFS.range,rang))

### Ajouter Individuals

In [ ]:
for i in range(len(df_individual)):
    c = URIRef(ns_url+df_individual.loc[i,'concept'].replace(" ","_"))
    ind = URIRef(ns_url+df_individual.loc[i,'individual'].replace(" ","_"))
    g.add((ind,RDF.type,c))

In [ ]:
for i in range(len(df_individual)):
    c = URIRef(ns_url+df_individual.loc[i,'concept'].replace(" ","_"))
    ind = URIRef(ns_url+df_individual.loc[i,'individual'].replace(" ","_"))
    g.add((ind,RDF.type,OWL.NamedIndividual))

In [ ]:
for j in range(len(df_objprop)):
    ind = URIRef(ns_url+df_objprop.loc[j,'Subject'].replace(" ","_"))
    obj = URIRef(ns_url+df_objprop.loc[j,'Object'].replace(" ","_"))
    objprop = URIRef(ns_url+df_objprop.loc[j,'Object Property'].replace(" ","_"))
    g.add((ind,objprop,obj))

In [ ]:
for j in range(len(df_dataprop)):
    ind = URIRef(ns_url+df_dataprop.loc[j,'Subject'].replace(" ","_"))
    obj = Literal(df_dataprop.loc[j,'Object'])
    dataprop = URIRef(ns_url+df_dataprop.loc[j,'Data Property'].replace(" ","_"))
    g.add((ind,dataprop,obj))

### Save

In [ ]:
with open('Ontology_PMBOKV2.0.owl', 'w', encoding='utf-8') as output:
    output.write(g.serialize(format="pretty-xml"))#.decode("utf-8"))

# START

In [ ]:
!pip install torch-geometric

In [ ]:
# Transform rdflib.Graph to  torch_geometric.data.Data
import networkx as nx
import torch
from torch_geometric.utils.convert import from_networkx

# Step 1: Extract graph structure from rdflib.Graph
edges = [(str(s), str(o)) for s, p, o in g]

# Step 2: Convert to NetworkX graph
G = nx.Graph()
G.add_edges_from(edges)

# Step 3: Convert to torch_geometric.data.Data
pyg_graph = from_networkx(G)

In [ ]:
# Train GNN model
import torch
from torch_geometric.nn import GCNConv

# Step 1: Define your GNN model
class GCN(torch.nn.Module):
    def __init__(self, num_node_features, num_classes):
        super(GCN, self).__init__()
        self.conv1 = GCNConv(num_node_features, 16)
        self.conv2 = GCNConv(16, num_classes)

    def forward(self, data):
        x, edge_index = data.x, data.edge_index
        x = self.conv1(x, edge_index).relu()
        x = self.conv2(x, edge_index)
        return x.log_softmax(dim=1)

# Assume 'data' is your torch_geometric.data.Data object
num_node_features = pyg_graph.num_node_features  # Number of node features
num_classes = len(set(pyg_graph.y.tolist()))  # Number of classes, assuming 'y' is the target

# Step 2: Prepare your data
# If you only have one graph, you don't need a DataLoader
# You can directly use your graph in the training loop

# Step 3: Train your model
model = GCN(num_node_features, num_classes)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.NLLLoss()

for epoch in range(100):
    optimizer.zero_grad()
    out = model(pyg_graph)
    loss = criterion(out[pyg_graph.train_mask], data.y[pyg_graph.train_mask])
    loss.backward()
    optimizer.step()
    print(f'Epoch: {epoch}, Loss: {loss.item()}')

# END

# Annotations

### Project risk manamgment annotation

In [ ]:
project_risk_manamgment_annotation=extract_text(text,"11PROJECT RISK MANAGEMENT","Figure 11").replace('˜','fi')

In [ ]:
project_risk_manamgment_annotation

### Annotation de chaque processus

In [ ]:
Processes_text=[PlanRiskManagement,IdentifyRisks,PerformQualitativeRiskAnalysis,PerformQuantitativeRisk,PlanRiskResponses,ImplementRiskResponses,MonitorRisks]

In [ ]:
annotation_processes=[]
for p in range(0,6):
    if p==0:
        s=extract_text(Processes_text[p],"1111."+str(p+1),"11."+str(p+2)+".1")
    else:
        s=extract_text(Processes_text[p],"11."+str(p+1),"11."+str(p+2)+".1")
    sep = 'depicts the data'
    stripped = s.split(sep, 1)[0]
    stripped=re.sub(r'.', '', stripped, count = len(extract_title(stripped))+1)
    annotation_processes.append(stripped.replace('˜','fi'))

In [ ]:
annotation_processes[0]

### Ajouter les annotation

In [ ]:
!pip install owlready2

In [ ]:
from owlready2 import *
onto_path.append("/kaggle/working/")
onto = get_ontology("/kaggle/working/Ontology_PMBOKV2.0.owl").load()

In [ ]:
len(list(onto.classes()))

### " Ajouter les annotations"

In [ ]:
onto.project_risk_management.comment = [project_risk_manamgment_annotation]
onto.plan_risk_management.comment =annotation_processes[0]
onto.identify_risks.comment =annotation_processes[1]
onto.perform_qualitative__risk_analysis.comment =annotation_processes[2]
onto.perform_quantitative__risk_analysis.comment =annotation_processes[3]
onto.plan_risk_responses.comment =annotation_processes[4]
onto.control_risks.comment =annotation_processes[5]

### Inputus,Outputs,Tools and Techniques annotation

In [ ]:
def reduce_text(test):
    #test=cleanMaj(test)
    test=test.replace('˚','fl').replace('˜','fi')
    test=test.strip()
    text=""
    sents=sent_tokenize(test)
    if len(sents)<5 :
        return test
    for sent in sent_tokenize(test)[:4]:
        text=text+" "+sent
    return text

In [ ]:
def cleanMaj(text):
    text=re.sub(r"(\w)([A-Z])", r"\1 \2", text)
    return text

In [ ]:
def extract_process_annotation(p,Type):
    if Type=="inputs":
        t=1
    elif Type=="tools and techniques":
        t=2
    elif Type=="outputs":
        t=3
    N=get_number(p,Type)
    titles=[]
    annotations=[]
    for i in range(1,N):
        start="11."+str(p)+"."+str(t)+"."+str(i)
        end="11."+str(p)+"."+str(t)+"."+str(i+1)
        annotation=extract_text(text2,start,end)
        titles.append(extract_title(annotation))
        if t==3:
            annotations.append(reduce_text(annotation.strip()))
        else:
            annotations.append(annotation.strip())    
    annotation=extract_text(text2,"11."+str(p)+"."+str(t)+"."+str(N),"11."+str(p)+"."+str(t+1))
    if t==3:
        annotation=reduce_text(annotation)
    titles.append(extract_title(annotation))
    annotations.append(annotation)
    return titles,annotations

In [ ]:
extract_process_annotation(1,"inputs")

In [ ]:
list_classes=list(onto.classes())
list_classes[:10]

In [ ]:
def annotation_ITTO(p,process,Type):
    for element in list(process.subclasses()):
        li=extract_process_annotation(p,Type)
        for Input in li[0]:
            if Input.lower().replace(' ','_') in str(element):
                #print(str(element))
                index=li[0].index(Input)
                element.comment.append(cleanMaj(li[1][index].replace('˚','fl').replace('˜','fi')) +" &P"+str(p))
                #element.comment=[]
                #print("*"*100)

### plan_risk_management

In [ ]:
annotation_ITTO(1,onto.plan_risk_management_inputs,"inputs")
annotation_ITTO(1,onto.plan_risk_management_tools_and_techniques,"tools and techniques")
annotation_ITTO(1,onto.plan_risk_management_outputs,"outputs")

### identify_risks

In [ ]:
annotation_ITTO(2,onto.identify_risks_inputs,"inputs")
annotation_ITTO(2,onto.identify_risks_tools_and_techniques,"tools and techniques")
annotation_ITTO(2,onto.identify_risks_outputs,"outputs")

### PerformQualitativeRiskAnalysis

In [ ]:
annotation_ITTO(3,onto.perform_qualitative__risk_analysis_inputs,"inputs")
annotation_ITTO(3,onto.perform_qualitative__risk_analysis_tools_and_techniques,"tools and techniques")
annotation_ITTO(3,onto.perform_qualitative__risk_analysis_outputs,"outputs")

### perform_quantitative__risk_analysis

In [ ]:
annotation_ITTO(4,onto.perform_quantitative__risk_analysis_inputs,"inputs")
annotation_ITTO(4,onto.perform_quantitative__risk_analysis_tools_and_techniques,"tools and techniques")
annotation_ITTO(4,onto.perform_quantitative__risk_analysis_outputs,"outputs")

### plan_risk_responses

In [ ]:
annotation_ITTO(5,onto.plan_risk_responses_inputs,"inputs")
annotation_ITTO(5,onto.plan_risk_responses_tools_and_techniques,"tools and techniques")
annotation_ITTO(5,onto.plan_risk_responses_outputs,"outputs")

### control_risks

In [ ]:
annotation_ITTO(6,onto.control_risks_inputs,"inputs")
annotation_ITTO(6,onto.control_risks_tools_and_techniques,"tools and techniques")
annotation_ITTO(6,onto.control_risks_outputs,"outputs")

In [ ]:
onto.save()

# Recommandation system

### Extraction des Mots clé

In [ ]:
from rake_nltk import Rake

In [ ]:
# Uses stopwords for english from NLTK, and all puntuation characters by
# default
r = Rake()

# Extraction given the text.
r.extract_keywords_from_text("what is the inputs of process risk managment plan")

In [ ]:
# To get keyword phrases ranked highest to lowest.
r.get_ranked_phrases()

In [ ]:
# To get keyword phrases ranked highest to lowest with scores.
r.get_ranked_phrases_with_scores()

In [ ]:
list_classes=list(onto.classes())
list_classes[:10]

In [ ]:
def change(w):
    w=str(w).replace('Ontology_PMBOKV2.0.','').replace('_',' ')
    return w

In [ ]:
list_classes_new=[change(classe) for classe in list_classes]
list_classes_new[:10]

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

docs = [(classe) for classe in list_classes_new ]
        
       

# TfidfVectorizer can be instanced with many useful parameters, e.g.,
# ngram_range (for ngram instead of 1-gram/word features), lowercase,
# min_df and max_df (for feature min/max document frequency filtering)
# strip_accents, tokenizer, norm (l1, l2 normalization), smooth_idf
# (on by default, additive smoothing), analyzer (which allows extracting
# character-level features, useful as morphological features).
tfidf_vectorizer = TfidfVectorizer(stop_words='english')
tfidf_matrix = tfidf_vectorizer.fit_transform(docs)

tfidf_matrix.shape

In [ ]:

# Lets compare the last document to all the other documents.
# As expected, the most similar document is 8, which shares
# since it's part of Sklearn's English stopwords. The other
# documents that have some similarity are 2 (shares 'war')


from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
from copy import copy

# Now lets try making a query with a new document. As

query = "what is identify risks"
query_vector = tfidf_vectorizer.transform([query])
list_sim=cosine_similarity(query_vector, tfidf_matrix)[0].tolist()

In [ ]:
max(list_sim)

In [ ]:
list_sim_tri=sorted(list_sim,reverse=True)

In [ ]:
list_sim_tri

In [ ]:
list_sim.index(list_sim_tri[0])

In [ ]:
list_classes_new[276]

In [ ]:
onto.identify_risks.comment

In [ ]:
list(onto.identify_risks.subclasses())

In [ ]:
for classe in onto.identify_risks_outputs.subclasses():
    print(classe.comment)

In [ ]:
def isSubOfProcess(classe):
    if ('inputs' in classe or ('outputs' in classe) or ('tools' in classe )):
        return True
    else :
        return False

In [ ]:
isSubOfProcess("plan risk inputs")

In [ ]:
def isProcess(classe):
    if classe in processes:
        return True
    else : 
        return False

In [ ]:
def get_process_name(classe):
    return classe.replace('tools and techniques','').replace('inputs','').replace('outputs','').strip()

In [ ]:
def list_Instance(instance):
    list_ancestors=instance.ancestors()
    list_ancestors=[change(value) for value in list_ancestors]
    list_ancestors =[ classe for classe in list_ancestors if ('inputs' in classe or ('outputs' in classe) or ('tools' in classe ) )]
    return list_ancestors

In [ ]:
spell("plen tt mangagment")

In [ ]:
def Recommande(query):
    query=spell(query)
    isSubProcess,isaProcess,is_instance,is_found=False,False,False,True
    concept=np.nan        
    query_vector = tfidf_vectorizer.transform([query])
    list_sim=cosine_similarity(query_vector, tfidf_matrix)[0].tolist()
    max_sim_term=max(list_sim)
    index= list_sim.index(max_sim_term) 
    keyword=list_classes_new[index]
    if(max_sim_term<0.2):
        is_found=False
    #print(keyword)
    #concept=RechercheOntology(keyword)
    concept=list_classes[index]
    if len(list_Instance(concept))>0 :
        is_instance=True
    if (concept!=np.nan):
        keyword=change(concept)
    if (isSubOfProcess(keyword)):
        isSubProcess=True
        is_instance=False
    if (isProcess(keyword)):
        isaProcess=True 
    
    return keyword,concept,[isaProcess,isSubProcess,is_instance],list_Instance(concept),is_found

In [ ]:
Recommande(" whats risk register")

In [ ]:
get_process_name(list(Recommande("control risks inputs"))[0])

In [ ]:
#onto.enterprise_environmental_factors.comment

In [ ]:
list_ancestors= list(onto.enterprise_environmental_factors.ancestors())
list_ancestors= [ change(classe) for classe in list_ancestors]
list_ancestors

In [ ]:
list_ancestors =[ classe for classe in list_ancestors if ('inputs' in classe or ('outputs' in classe) or ('tools' in classe ) )]
#list_ancestors = [ classe.replace('tools and techniques','').replace('inputs','').replace('outputs','').strip() for classe in list_ancestors]

In [ ]:
list_ancestors

In [ ]:
dict_processes={'plan risk management':'&P1',
 'identify risks':'&P2',
 'perform qualitative  risk analysis':'&P3',
 'perform quantitative  risk analysis':'&P4',
 'plan risk responses':'&P5',
 'control risks':'&P6'}

In [ ]:
dict_processes.get('perform quantitative  risk analysis')

In [ ]:
onto.enterprise_environmental_factors.comment[0]

In [ ]:
list(Recommande("project documents updates"))

In [ ]:
def get_subclasses(Type,classe):
    list_subclasses=[]
    for element in classe.subclasses():
        if Type in change(str(element)):
            for value in element.subclasses():
                list_subclasses.append(change(str(value)))
    return list_subclasses

In [ ]:
def get_annotation(process,list_annotation):
    for annotation in list_annotation:
        if (dict_processes.get(process) in  annotation):
            return annotation
    return ""

In [ ]:
def get_list_annotation(process,process_sub):
    list_annotations=[]
    for element in process_sub.subclasses():
        list_annotations.append(get_annotation(process,element.comment))
    return list_annotations

In [ ]:
get_subclasses("tools and techniques",onto.control_risks)

In [ ]:
for element in onto.control_risks_inputs.subclasses():
    process=get_process_name('control risks inputs')
    print(element)
    annotation=get_annotation(process,element.comment)
    print(annotation)

In [ ]:
get_list_annotation('control risks',onto.control_risks_inputs)

In [ ]:
get_annotation('perform quantitative  risk analysis',onto.enterprise_environmental_factors.comment)

In [ ]:
onto.project_documents_updates.ancestors()

In [ ]:
list_Instance(onto.project_documents_updates)

In [ ]:
comment=onto.enterprise_environmental_factors.comment[0]
comment

In [ ]:
comment2=onto.identify_risks.comment[0]
comment2

In [ ]:
table_figures=""
for i in range(15,26):
    my_page = pdfReader.getPage(i)
    table_figures=table_figures+my_page.extractText()
table_figures=table_figures.replace("\n"," ").replace("..","")

In [ ]:
def to_int(text):
    page=""
    i=0
    for s in text:
        if(s.isdigit()):
            page=page+s
            i=i+1
            if(i==3):
                break;
    page=int(page)
    return page

In [ ]:
#extraction de la num page figure
def extracy_figure_page(annotation,table_figures):
    dict_Figure={}
    listF=re.findall(r'Figure +.[0-9]+-[0-9].', annotation)
    for figure in listF:
        figure=figure.replace('.','').strip()
        last_number=int(figure[-1])
        page=extract_text(table_figures,figure,figure[:-1]+str(last_number+ 1))
        dict_Figure[figure]=to_int(page)+26
    return dict_Figure

In [ ]:
annotation_processes[1]

In [ ]:
extracy_figure_page(annotation_processes[1],table_figures)

In [ ]:
writer = PyPDF2.PdfFileWriter()
Context=""
for i in range(4,25):
    my_page = pdfReader.getPage(i)
    Context=Context+my_page.extractText()
Context=Context.replace("\n"," ").replace("..","")

In [ ]:
#extraction de la num page pour le section
def get_section_page(comment):
    if "Section" in comment:
        section=extract_text(comment,"Section",". ").strip()+" "
        index=0
        n=int((section).split('.')[0])
        l=[]
        if n in range(1,5):
            l=[27,130]
        elif n in range(5,8):
            l=[130,252]
        elif n in range(8,12):
            l=[253,380]
        else :
            l=[381,500]
        for i in range(l[0],l[1]):        
            page=pdfReader.getPage(i)
            if (section in page.extractText()):
                index=i
                return index+1

    return

In [ ]:
comments=get_list_annotation(get_process_name(Recommande("control risks inputs")[0]),Recommande("control risks inputs")[1])

In [ ]:
comments[1]

In [ ]:
get_section_page(comments[1])